spring.datasource.url=jdbc:postgresql://dpg-d72gebdm5p6s73d1ai8g-a.singapore-postgres.render.com/sqms_backend
spring.datasource.username=sqms_backend_user
spring.datasource.password=msjbd8b8LPBg44ORDb8xurE8BvRWQqVN
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}